sudo: false
language: node_js
node_js: 
  - 14
branches:
  only:
  - hexo
install:
- npm i
- npm install hexo-deployer-git --save
- cd ./themes
- rm -rf Next
- git clone https://github.com/recursively/hexo-theme-next.git Next
- cd Next
- sed -i "s/hidden_client_id/${client_id}/g" ./_config.yml
- sed -i "s/hidden_client_secret/${client_secret}/g" ./_config.yml
- cd ../../
# - cd -
# - cd ./themes/Next/source/lib
# - rm -rf three
# - git clone https://github.com/recursively/theme-next-three.git three
script:
- hexo clean
- hexo generate
after_script:
- git config user.name "recursively"
- git config user.email "reindeer.zyh@gmail.com"

- sed -i "s/gh_token/${REPO_TOKEN}/g" ./_config.yml
- hexo deploy

