sudo: false
language: node_js
node_js: stable
branches:
  only:
  - hexo
install:
- npm i
- npm install hexo-deployer-git --save
- cd ./themes
- git clone https://github.com/recursively/hexo-theme-next.git Next
- cd -
- cd ./themes/Next/source/lib
- git clone https://github.com/recursively/theme-next-three.git three
- cd -
script:
- hexo clean
- hexo generate
after_script:
- git config user.name "recursively"
- git config user.email "reindeer.zyh@gmail.com"

- sed -i "s/gh_token/${REPO_TOKEN}/g" ./_config.yml
- hexo deploy

